[build]
  command = "npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_OMIT_KEYS = "SANITY_API_READ_TOKEN,CLOUDINARY_API_SECRET,CLOUDINARY_API_KEY" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
